apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: openshift
    folders: openshift
    instance: grafana
  name: grafana
spec:
  config:
    auth:
      disable_login_form: 'false'
      disable_signout_menu: 'false'
    log:
      mode: console
    security:
      admin_password: admin
      admin_user: admin
  route:
    spec: {}
  deployment:
    spec:
      template:
        spec:
          containers:
          - image: 'grafana/grafana:latest'
            name: grafana