{
 "title": "OpenShift Ingress (HAProxy)",
 "description": "A dashboard for OpenShift Ingress/Route (HAProxy) monitoring.",
 "tags": [
  "openshift",
  "ingress",
  "route",
  "haproxy",
  "backend",
  "server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,2h,5h,8h,12h,15h,20h,1d"
   },
   { "name": "pod", "label": "Router", "query": "label_values(haproxy_up, pod)" },
   {
    "name": "namespace",
    "label": "Project",
    "query": {
     "query": "label_values(haproxy_backend_up,exported_namespace)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(haproxy_backend_up{exported_namespace=~\"$namespace\"},route)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_up{pod=~\"$pod\", exported_namespace=~\"$namespace\"},backend)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_backend_http_responses_total{pod=~\"$pod\", backend=~\"$backend\"},code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Router Pod Started Date Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"$pod\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Router Container Started/Restarted Date Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_start_time_seconds{pod=~\"$pod\", container=\"router\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HAProxy Process Started/Reloaded Date Time",
   "type": "stat",
   "description": "When was the last date and time HAProxy process reloaded",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_process_start_time_seconds{pod=~\"$pod\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Router Pod Container Restart Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$pod\", container=\"router\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Router Container Uptime Since Last Started/Restarted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{pod=~\"$pod\", container=\"router\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HAProxy Process Uptime Since Last Started/Reloaded",
   "type": "stat",
   "description": "How long the HAProxy process has been started since last reloaded",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Route Per Project",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(haproxy_backend_up{pod=~\"$pod\", exported_namespace=~\"$namespace\"}) by (exported_namespace, route)) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Total Route",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(haproxy_backend_up{pod=~\"$pod\", exported_namespace=~\"$namespace\"}) by (route, exported_namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total of Backend Connection Errors",
   "type": "stat",
   "description": "Total of connection errors when HAProxy was not able to connect to backend i.e. pod(s)",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_backend_connection_errors_total{pod=~\"$pod\", exported_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Total Outgoing Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_server_bytes_out_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Total Incoming Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_server_bytes_in_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}